<a href="https://colab.research.google.com/github/Jules-gatete/Participation-Assignment/blob/main/Participation_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Participation Assignment**

**Names:**



*   Jules Gatete
*   Josiane Ishimwe




In [8]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn

In [9]:
#import data
path = "/content/Housing.csv"
data = pd.read_csv(path)

data.head(10)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no   
1  12250000   8960         4          4        4      yes        no       no   
2  12250000   9960         3          2        2      yes        no      yes   
3  12215000   7500         4          2        2      yes        no      yes   
4  11410000   7420         4          1        2      yes       yes      yes   
5  10850000   7500         3          3        1      yes        no      yes   
6  10150000   8580         4          3        4      yes        no       no   
7  10150000  16200         5          3        2      yes        no       no   
8   9870000   8100         4          1        2      yes       yes      yes   
9   9800000   5750         3          2        4      yes       yes       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
5              no             yes        2      yes   semi-furnished  
6              no             yes        2      yes   semi-furnished  
7              no              no        0       no      unfurnished  
8              no             yes        2      yes        furnished  
9              no             yes        1      yes      unfurnished

In [10]:
# Define X (features) and y (target)
X = data.drop('furnishingstatus', axis=1)
y = data['furnishingstatus']
num_classes = len(set(y))

In [12]:
# Encode categorical features in X
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
categorical_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
X[categorical_cols] = X[categorical_cols].apply(label_encoder.fit_transform)

# Normalize the numerical features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


    # One-hot encode the target variable
from tensorflow.keras.utils import to_categorical
y_encoded = label_encoder.fit_transform(y)
y_one_hot = to_categorical(y_encoded)


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# Define the Sequential model
model = Sequential()

# Input Layer
model.add(Dense(128, activation='relu', input_shape=(X_scaled.shape[1],)))

# Hidden Layer
model.add(Dense(128, activation='relu'))

# Output Layer
model.add(Dense(num_classes, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# Compile the model
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [16]:
# Train the model
model.fit(X_scaled, y_one_hot, epochs=20, batch_size=32, validation_split=0.2)


Epoch 1/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.4132 - loss: 1.1042 - val_accuracy: 0.2202 - val_loss: 1.1612
Epoch 2/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4545 - loss: 1.0345 - val_accuracy: 0.2202 - val_loss: 1.1820
Epoch 3/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5053 - loss: 0.9906 - val_accuracy: 0.2202 - val_loss: 1.1130
Epoch 4/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5271 - loss: 0.9729 - val_accuracy: 0.3486 - val_loss: 1.1005
Epoch 5/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5621 - loss: 0.9524 - val_accuracy: 0.3670 - val_loss: 1.0772
Epoch 6/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5552 - loss: 0.9429 - val_accuracy: 0.3945 - val_loss: 1.0681
Epoch 7/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5843 - loss: 0.9256 - val_accuracy: 0.4771 - val_loss: 1.0527
Epoch 8/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6021 - loss: 0.9069 - val_accuracy: 0.4495 - val_loss

In [17]:
# Save the model
model.save('furnishing_model.h5')

In [18]:
# predictions
predictions = model.predict(X_scaled[:5])
print("Predictions (probabilities):", predictions)

# Decode predictions to class labels
predicted_classes = np.argmax(predictions, axis=1)
print("Predicted Classes:", label_encoder.inverse_transform(predicted_classes))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
Predictions (probabilities): [[0.7462611  0.23042823 0.02331059]
 [0.8382883  0.08223113 0.07948048]
 [0.43171978 0.5108756  0.05740464]
 [0.7213164  0.26190165 0.01678202]
 [0.87723815 0.04361511 0.07914683]]
Predicted Classes: ['furnished' 'furnished' 'semi-furnished' 'furnished' 'furnished']


In [ ]:
# Save the model
model.save('furnishing_status_model.h5')

In [19]:
# Load the model from the file

from tensorflow.keras.models import load_model
loaded_model = load_model("furnishing_model.h5")


In [20]:
# Check the model summary
loaded_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           1,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │             387 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 18,565 (72.52 KB)

 Trainable params: 18,563 (72.51 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)